### ISSUE TITLE
"Analyze" is showing "cartodb_id" in helper's dropdown

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#168]
## STR

1. Create a map from a dataset
2. Click on "Analyze"
3. Choose "Choropleth" helper
4. Display the column dropdown menu

## Expected behaviour 

A variety of columns are displayed to choose from, not including "cartodb_id".

## Actual result

"cartodb_id" is shown as a selectable option.

@coyle5280 it seems like this has broken recently. Could you take a look?

**Comment by coyle5280** [comment]
See PR for acceptance notes.  This fixes the issue where `cartodb_id` was showing in the analyze drop down but I am still seeing an issue where the initial selection of an analyze category produces an sql error. Not sure if this issue is being reproduced on the final Bloomberg terminal.  The SQL generation error appears to be unrelated to the inclusion of the `cartodb_id` choice.
