### ISSUE TITLE
[Aliases] Possible bug in aliasing code

### ISSUE THREAD

**Issue by gfiorav** [cartodb-org/cartodb#179]
## Context

Please revise, you might find it useful for some other related issues:

Original text 1:
```
Since `extra` was converted to a 2d array for the propagation of aliases, the following check to see whether a currently selected column value for a form as stored in `WizardProperties` will always fail:
* [WizardProperties#_updateForm](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/models/wizard.js#L357)

Note that the resolution of this issue is contingent upon the structure of `extra` being finalized in https://github.com/CartoDB/cartodb-bloomberg/issues/245.
```

Original text 2:

```
In many cases, the `extra` values, or allowed values/options of a form contain both flat strings e.g. "None" to indicate no selection or an array of names/aliases when the choices are columns, such as:


extra = [ "None", ["col_name", "col_name", "alias"], ... ];

As per [FormSchema#_fillColumns](https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/models/wizard.js#L84), this is the case when `extra_default` is set on the forms. A couples examples are:
* https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/table/menu_modules/carto_wizard_forms.js#L59
* https://github.com/bloomberg/cartodb/blob/blp_dev/lib/assets/javascripts/cartodb/table/menu_modules/carto_wizard_forms.js#L247

You should be able to observe this on creating a new map with an empty dataset and stepping through the `_fillColumns` code.

I haven't directly observe a bug resulting from this structure. However, on our call yesterday, Josh agreed that this didn't seem like the intended behavior of the `extra` values, in which case I think it should be investigated further to ensure that it works as designed and that the current behavior cannot cause any issues.
```

**Comment by gfiorav** [comment]
@coyle5280, the second one has been resolved by them. Could you review? https://github.com/bloomberg/cartodb/pull/183/files

**Comment by coyle5280** [comment]
So after some research I think I understand what is happening here with the `'None'` value.  In the wizards certain drop downs or 'Select' fields need a null/empty/None field for the selection.  In order to offer this choice to the user the `'None'` value needs to be injected into the list of possible choices or columns.  If you look at the `label` field for the simple wizard you will see that the default choice is None.  If I understand there code they would remove this option from the list of choices. This might break the wizard by not allowing you to remove the label field.  If it's not broke don't fix it!!  But if they insist on the array being homogeneous then I would say we make the change you see in branch `179_possible_bug`.  I tested this out and did not see any issues with this implementation.  I would not recommend there implementation without testing wizards. Especially the label fields or any field that uses a 'None' value.

**Comment by gfiorav** [comment]
Thanks, I forwarded your comments to Bloomberg. If you can write comments on https://github.com/bloomberg/cartodb/pull/183/files directly, feel free to do so. For this one I just quoted you (with a bit of changes here and here), but just write on those lines directly next time :)

**Comment by gfiorav** [comment]
Do you have any input on "Original Text 1"?
