### ISSUE TITLE
[Filters] Up/down arrows on increment control for Histogram

### ISSUE THREAD

**Issue by alissarose** [cartodb-org/cartodb#186]
### context
When a user is presented with Histogram for searching, the increment controls on the ranges are not visible. The two values should have up & down facing arrows on the button.
> note: Will update with screenshot

### approach
tbd - @gfiorav to update Josh on call + update ticket with relevant details

**Comment by alissarose** [comment]
hey @coyle5280 sorry for the delay. below is a screenshot of what they were asking - basically you can adjust the numbers up&down but the controls aren't visible

![screen shot 2017-10-20 at 10 53 12 am](https://user-images.githubusercontent.com/6743887/31827319-63e71756-b585-11e7-83a9-7b06210689e4.png)

**Comment by coyle5280** [comment]
@alissarose @gfiorav The issue here is the custom styling that was added by `mbekyas` in commit `83367b7fe7b631aa57164bbfd4a99171ff63caa5` to file `app/assets/stylesheets/common/default.css.scss`.  The custom styling is incomplete.  Looks like this style was added on 8/1/2016.  I am hesitant to change it because I do not know why the original style was overridden.  Is it possible to get a little more info on why this was added?  What was the original component for this style change?  Since this issue is with style added by bloomberg should I continue to work on it or should it be passed back to BB?  Let me know your thoughts. Thanks! 
![capture](https://user-images.githubusercontent.com/11877788/31964510-72dc1ce0-b8c1-11e7-9c28-1c1b6cf12d5e.JPG)

**Comment by alissarose** [comment]
thanks for letting us know @coyle5280 

@gfiorav do you want to reach out to mehmet or should i?

**Comment by gfiorav** [comment]
In case of doubt we can always create a new class and use that. Could you do that @coyle5280 ?
