### ISSUE TITLE
Numeric filtering updates

### ISSUE THREAD

**Issue by mbforr** [cartodb-org/cartodb#28]
Lesser custom range doesn't retain inputted value, auto-goes back to prior interval
Left increment bar snapped to different values than right increment bar

@javisantana

**Comment by jbranigan** [comment]
Figure out what event is causing the slider to snap when the view is reinitialized

**Comment by CloudNiner** [comment]
It seems like the core issue here is that we have no way to get which of the two grabbers is being dragged, and therefore only update the extent on that value. There's nothing I can see in the d3.svg.brush library, or a way to get at the dom event that the user clicked via the brush event handler. The current solution works because we are able to compare against the initial extent of the grabber when the dragging starts. If we also snap the extent to the histogram bins, we lose the ability to make this comparison because values have changed and the detection of which grabber we're dragging becomes ambiguous. 

Here is a screencapture of the bugfix with no bin snapping. If that is sufficient I'll submit a PR for this, otherwise I can continue to look at it.

![bb-num-filters-1](https://cloud.githubusercontent.com/assets/1818302/15259039/ef74d47c-191c-11e6-8169-df9ce180db8e.gif)

**Comment by mbforr** [comment]
I think this looks good @CloudNiner

**Comment by CloudNiner** [comment]
@mbforr A fix was merged for this awhile back. Can this be closed or does it need additional work?

**Comment by mbforr** [comment]
Yeah that works - we have some time blocked out for that later on in this
phase.

On Thu, Jun 16, 2016 at 9:18 AM, Andrew Fink notifications@github.com
wrote:

> @mbforr https://github.com/mbforr A fix was merged for this awhile
> back. Can this be closed or does it need additional work?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/cartodb-org/cartodb/issues/28#issuecomment-226482255,
> or mute the thread
> https://github.com/notifications/unsubscribe/AEmtLD1I6_24U5bG0wlGQkqEsCtHD8Quks5qMU0_gaJpZM4Iasg_
> .

## 

_Matt Forrest_
Client Success Manager

_CartoDB_
201 Moore St, Brooklyn, NY, 11206, USA
T: (612) 325-8470 Skype: mbforr
W: www.cartodb.com

Live sessions to learn CartoDB http://cartodb.com/webinars/
