### ISSUE TITLE
Legend Formatting

### ISSUE THREAD

**Issue by jbranigan** [cartodb-org/cartodb#5]
Similar to other formatting options the client would like the option to configure the map legend with the following options:
- Legend position in any of the 4 corners of the map
- Legend background color (incl. transparent)
- Legend border color
- Typeface and type color
- Type size (limited options)
  - This could be some select legend sizes as well (large, medium, small)

**Comment by mbforr** [comment]
![screen shot 2016-02-10 at 11 38 14 am](https://cloud.githubusercontent.com/assets/4828460/12954025/e696c494-cfea-11e5-887f-edcf01d20858.png)

**Comment by mbforr** [comment]
We also need to add in the ability to turn on and off the border - both stroke and shadow so basically a plain box that uses the color specified by the user.

**Comment by mbforr** [comment]
If you could send a screen shot of this feature that would be great (I'll post this on the other open issues too.)

**Comment by flibbertigibbet** [comment]
The movable legend: 
![image](https://cloud.githubusercontent.com/assets/960264/14087283/23dca7ac-f4f7-11e5-88e4-80c2d29d9a8d.png)

**Comment by CloudNiner** [comment]
#22 now allows the user to edit the items requested above, as well as drag to a custom position on the map. It is up to the user to avoid collisions of the legend with other overlays/map objects. 

The easiest way to allow the user to reset the legend to its default formatting was to provide a popup "X" button that only appears when you hover over the legend. I just left this mostly unstyled since there wasn't an existing asset for it, I figure the client can apply their custom css stylings and do whatever with it. If we need to style this up, we should be able to do that.

Make the styling bar appear by clicking on the legend, make it disappear by clicking anywhere on the map, just like for annotations.

Between the draggable plugin and the existing styling of the page, the legend takes on a fixed width/height once it is dragged. Additional width/height controls were added to the toolbar, since if text, etc is modified they will overflow the legend. These additional width/height controls allow the user to tweak the legend size so that the legend items stay within the legend div.

Screenshots:
![bb-styled-legend](https://cloud.githubusercontent.com/assets/1818302/14262071/ad4f6e72-fa81-11e5-8d8c-c130017df04b.png)
![bb-legend-reset](https://cloud.githubusercontent.com/assets/1818302/14262072/af671386-fa81-11e5-83d6-c3c03f6879d5.png)

**Comment by CloudNiner** [comment]
Also note that #22 introduces a database migration and requires an update to the cartodb.js subproject

**Comment by flibbertigibbet** [comment]
Making a format change after a legend drag without first clicking away still causes legend to jump to last saved location.

The reset button is centered in its box when the legend is in the bottom right, but floats to the top left after the legend moves.
